### ISSUE TITLE
Computer cart doesn't recognise when it's no longer on electric track.

### ISSUE THREAD

**Issue by cloakable** [feldim2425/OC-Minecarts#13]
Running a computer cart on electric track charges it as usual, but when it leaves the electric track, it continues to recharge.

ocminecart-1.5-oc1.5
OpenComputers-MC1.7.10-1.5.22.46-universal
Railcraft_1.7.10-9.12.2.0

**Comment by feldim2425** [comment]
There is a small buffer. I think 1000 EU. It will stop when the buffer is empty. Wait a minute and it should stop.

**Comment by cloakable** [comment]
Aha, thanks.
