### ISSUE TITLE
Error in inventory count

### ISSUE THREAD

**Issue by dustpuppy** [feldim2425/OC-Minecarts#16]
Hi,
i've found an error in the count() method.
Not easy to explain :-) 
Source is : 

local component = require("component")
local cart = component.computercart
for i = 1, cart.inventorySize() do
    print(i, cart.count(i))
end

The first slot (i=1) will give an error "no slot selected". So i did it from 2.
Count is not starting at slot 1. It goes from slot 2 to inventorySize + 1. 
Possible picture will explain it better ;-) 
![bildschirmfoto13](https://cloud.githubusercontent.com/assets/1313596/17273133/ee01d9f0-56a2-11e6-9a69-f604642a60f8.png)

**Comment by feldim2425** [comment]
In my test it throws an error ("invalid slot").
"no slot selected" means that you called count() without arguments and the selected slot is invalid.

But you are right the slot index is one off. I will fix that.

**Comment by feldim2425** [comment]
Fix in version 1.6
