### ISSUE TITLE
strange glow of entitys

### ISSUE THREAD

**Issue by Timmy94W** [feldim2425/OC-Minecarts#2]
![what](https://cloud.githubusercontent.com/assets/6671741/10121675/59fc61f4-64f8-11e5-9a19-743b9c006bb0.png)
i have notice this a few minutes ago. If the Computer Cart as an entity on the tracks, other entitys become a strange glowing, see-through effect.

**Comment by feldim2425** [comment]
I can not reproduce it, but I think I found the bug in the code. Do you have the same problem if the computer cart is turned off?

**Comment by Timmy94W** [comment]
I don't have this Problem, when the Cart is turned off

**Comment by feldim2425** [comment]
That means that I am a idiot. I forgot to disable glBlend after rendering the colored cube.

**Comment by feldim2425** [comment]
This should fix it.

**Comment by Timmy94W** [comment]
and a other think, that doesnt belongs here: If you recycle the tier 1 cart, you will get a tier 2 cart
and when you assemble a tier 1 cart, you will get a tier 2 cart too

**Comment by feldim2425** [comment]
Can you please write a new issue for that.
