### ISSUE TITLE
[Suggestion] Lock/Unlock command

### ISSUE THREAD

**Issue by JomerDev** [feldim2425/OC-Minecarts#5]
It would be a really nice feature to have a lock/unlock command. Maybe a new Component? 
It would lock/unlock the last cart in the specified direction.

So maybe

lockFront(number?) 
unlockFront(number?)
lockBack(number?)
unlockBack(number?)

The number would be the number of carts to lock/unlock. So one could have 5 carts on an OCCart an unlock them all from the OCCart, while leaving them locked to themself.

For that you would maybe have a function getCartCountFront() and getCartCountBack() so one can check how many carts he is pulling.

That would make the OCCarts much more usefull for Trains and shunting of carts

**Comment by feldim2425** [comment]
DONE
released version 0.8-beta
