### ISSUE TITLE
Failed to load extended properties for ocminecart.RCcart

### ISSUE THREAD

**Issue by Alaberti** [feldim2425/OC-Minecarts#6]
Getting this issue in my dedicated server console: http://pastebin.com/UejU2WJu

OC Minecarts 1.0, Forge 1566.

**Comment by feldim2425** [comment]
Version 1.1 is now available on [Curse](http://minecraft.curseforge.com/projects/oc-minecarts/files/2272162).

**Comment by Alaberti** [comment]
Thank you! Happy holidays!
