### ISSUE TITLE
Crash when inserting Beep Card

### ISSUE THREAD

**Issue by JomerDev** [feldim2425/OC-Minecarts#9]
I just had a server crash when I inserted a Beep Card by Computronics in a Card Container Tier 2 in a Tier 2 oc-minecart.

After restarting the cart was gone

Crashlog:
https://www.dropbox.com/s/bo4slolnhhkdtv0/crash-2016-03-15_18.58.37-server.txt?dl=0

**Comment by feldim2425** [comment]
Does it work in a Robot / Computer / Drone ?

EDIT: Maybe Computronics doesn't work with OC 1.6 .

**Comment by JomerDev** [comment]
Yeah, it also crashes with robots. It probably isn't updated for 1.6.
Sorry for the confusion
